version: "3.9"
services:
  db:
    image: timescale/timescaledb:2.11.1-pg15
    environment:
      POSTGRES_PASSWORD: trader
      POSTGRES_USER: trader
      POSTGRES_DB: trader
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "trader"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: backend.Dockerfile
    env_file:
      - .env.example
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ..
      dockerfile: frontend.Dockerfile
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:3000"

volumes:
  db_data:
